#include "lang.h"
#include <string.h>

#define LANG_ES 0
#define LANG_EN 1
#define LANG_FR 2

static int g_lang = LANG_ES;

static const char* s_strings[3][STR_COUNT] = {
    /* ===== ES ===== */
    {
        /* STR_SUBTITLE */           "Juego de Cartas Multiplayer",
        /* STR_BTN_PLAY */           "JUGAR",
        /* STR_BTN_INSTRUCTIONS */   "INSTRUCCIONES",
        /* STR_BTN_SETTINGS */       "CONFIGURACION",
        /* STR_HINT_ENTER_START */   "Presiona ENTER para comenzar",
        /* STR_HINT_BEST_HAND */     "Forma la mejor mano de 5 cartas con 8 cartas repartidas",
        /* STR_HOW_TO_PLAY_TITLE */  "COMO JUGAR",
        /* STR_OBJ_LABEL */          "Objetivo:",
        /* STR_OBJ_TEXT */           "Forma la mejor mano de poker con las cartas que tienes.",
        /* STR_HOW_TO_PLAY_SECTION */"COMO JUGAR:",
        /* STR_INSTR_1 */            "1. Recibes 8 cartas",
        /* STR_INSTR_2 */            "2. Selecciona 1-5 cartas para formar tu mano",
        /* STR_INSTR_3 */            "3. Puedes DESCARTAR hasta 5 cartas UNA vez",
        /* STR_INSTR_4 */            "4. Presiona CONFIRMAR para jugar tu mano",
        /* STR_HANDS_SECTION */      "MANOS Y PUNTOS:",
        /* STR_HANDS_LINE1 */        "Carta Alta: 0 pts      Pareja: 100 pts     Doble Pareja: 200 pts",
        /* STR_HANDS_LINE2 */        "Trio: 300 pts          Escalera: 400 pts   Color: 500 pts",
        /* STR_HANDS_LINE3 */        "Full House: 600 pts    Poker: 800 pts      Escalera de Color: 900 pts",
        /* STR_HANDS_LINE4 */        "",
        /* STR_CONTROLS_SECTION */   "CONTROLES:",
        /* STR_CTRL_MOUSE */         "Raton: Click en cartas para seleccionar",
        /* STR_CTRL_BUTTONS */       "Botones: Usa los botones verdes para continuar",
        /* STR_CTRL_ENTER */         "Enter: Tambien puedes presionar ENTER",
        /* STR_BTN_BACK */           "ATRAS",
        /* STR_BTN_RETURN */         "VOLVER",
        /* STR_BTN_CONTINUE */       "CONTINUAR",
        /* STR_BTN_NEXT */           "SIGUIENTE",
        /* STR_BTN_CONFIRM */        "CONFIRMAR",
        /* STR_BTN_DISCARD */        "DESCARTAR",
        /* STR_BTN_READY */          "ESTOY LISTO",
        /* STR_BTN_PLAY_AGAIN */     "JUGAR DE NUEVO",
        /* STR_AUDIO_SETTINGS */     "CONFIGURACION DE AUDIO",
        /* STR_LABEL_MUSIC */        "Musica:",
        /* STR_HINT_ADJUST */        "Usa las flechas o botones + y - para ajustar",
        /* STR_SETUP_TITLE */        "CONFIGURACION",
        /* STR_FMT_PLAYERS */        "Jugadores: %d",
        /* STR_FMT_ROUNDS */         "Rondas: %d",
        /* STR_FMT_TARGET */         "Obj: %d pts",
        /* STR_HINT_TAB_ARROWS */    "Usa TAB para cambiar opcion, FLECHAS para ajustar",
        /* STR_BTN_SORT_VALUE */     "VALOR",
        /* STR_BTN_SORT_SUIT */      "PALO",
        /* STR_DEALING */            "Repartiendo cartas...",
        /* STR_FMT_ROUND_OF */       "Ronda %d de %d",
        /* STR_FMT_TURN */           "Turno de: %s",
        /* STR_FMT_HAND_NO_POINTS */ "%s (sin puntos)",
        /* STR_FMT_SELECTED */       "Seleccionadas: %d/5",
        /* STR_HINT_SELECT_CARDS */  "Selecciona 1-5 cartas para formar tu mano",
        /* STR_HINT_CAN_DISCARD */   "Puedes descartar hasta 5 cartas",
        /* STR_FMT_PASS_DEVICE */    "Pasa el dispositivo a %s",
        /* STR_ROUND_RESULTS */      "RESULTADOS DE LA RONDA",
        /* STR_FMT_ROUND */          "Ronda %d",
        /* STR_FMT_PLAYER_RESULT */  "%s - Puntos: +%d (Total: %d)",
        /* STR_HINT_ENTER_CONTINUE */"Presiona ENTER para continuar",
        /* STR_GAME_OVER */          "FIN DEL JUEGO",
        /* STR_FMT_WINNER */         "Ganador: %s con %d puntos!",
        /* STR_FMT_FINAL_SCORE */    "%s: %d puntos (%d rondas ganadas)",
        /* STR_HINT_RESTART */       "Presiona ENTER o R para reiniciar",
        /* STR_SCOREBOARD */         "PUNTUACION",
        /* STR_HIGH_SCORES */        "MEJORES PUNTUACIONES",
        /* STR_HS_PLAYER */          "Jugador",
        /* STR_HS_POINTS */          "Puntos",
        /* STR_HS_DATE */            "Fecha",
        /* STR_HS_EMPTY */           "No hay puntuaciones registradas",
        /* STR_HAND_HIGH_CARD */     "Carta Alta",
        /* STR_HAND_ONE_PAIR */      "Pareja",
        /* STR_HAND_TWO_PAIR */      "Doble Pareja",
        /* STR_HAND_THREE_KIND */    "Trio",
        /* STR_HAND_STRAIGHT */      "Escalera",
        /* STR_HAND_FLUSH */         "Color",
        /* STR_HAND_FULL_HOUSE */    "Full House",
        /* STR_HAND_FOUR_KIND */     "Poker",
        /* STR_HAND_STRAIGHT_FLUSH */"Escalera de Color",
        /* STR_HAND_UNKNOWN */       "Desconocido",
    },
    /* ===== EN ===== */
    {
        /* STR_SUBTITLE */           "Multiplayer Card Game",
        /* STR_BTN_PLAY */           "PLAY",
        /* STR_BTN_INSTRUCTIONS */   "INSTRUCTIONS",
        /* STR_BTN_SETTINGS */       "SETTINGS",
        /* STR_HINT_ENTER_START */   "Press ENTER to start",
        /* STR_HINT_BEST_HAND */     "Form the best 5-card hand from 8 dealt cards",
        /* STR_HOW_TO_PLAY_TITLE */  "HOW TO PLAY",
        /* STR_OBJ_LABEL */          "Goal:",
        /* STR_OBJ_TEXT */           "Form the best poker hand from your cards.",
        /* STR_HOW_TO_PLAY_SECTION */"HOW TO PLAY:",
        /* STR_INSTR_1 */            "1. You receive 8 cards",
        /* STR_INSTR_2 */            "2. Select 1-5 cards to form your hand",
        /* STR_INSTR_3 */            "3. You can DISCARD up to 5 cards ONCE",
        /* STR_INSTR_4 */            "4. Press CONFIRM to play your hand",
        /* STR_HANDS_SECTION */      "HANDS & POINTS:",
        /* STR_HANDS_LINE1 */        "High Card: 0 pts       Pair: 100 pts       Two Pair: 200 pts",
        /* STR_HANDS_LINE2 */        "3 of a Kind: 300 pts   Straight: 400 pts   Flush: 500 pts",
        /* STR_HANDS_LINE3 */        "Full House: 600 pts    4 of a Kind: 800    Straight Flush: 900",
        /* STR_HANDS_LINE4 */        "",
        /* STR_CONTROLS_SECTION */   "CONTROLES:",
        /* STR_CTRL_MOUSE */         "Mouse: Click on cards to select",
        /* STR_CTRL_BUTTONS */       "Buttons: Use green buttons to continue",
        /* STR_CTRL_ENTER */         "Enter: You can also press ENTER",
        /* STR_BTN_BACK */           "BACK",
        /* STR_BTN_RETURN */         "RETURN",
        /* STR_BTN_CONTINUE */       "CONTINUE",
        /* STR_BTN_NEXT */           "NEXT",
        /* STR_BTN_CONFIRM */        "CONFIRM",
        /* STR_BTN_DISCARD */        "DISCARD",
        /* STR_BTN_READY */          "I'M READY",
        /* STR_BTN_PLAY_AGAIN */     "PLAY AGAIN",
        /* STR_AUDIO_SETTINGS */     "AUDIO SETTINGS",
        /* STR_LABEL_MUSIC */        "Music:",
        /* STR_HINT_ADJUST */        "Use arrows or + and - buttons to adjust",
        /* STR_SETUP_TITLE */        "SETTINGS",
        /* STR_FMT_PLAYERS */        "Players: %d",
        /* STR_FMT_ROUNDS */         "Rounds: %d",
        /* STR_FMT_TARGET */         "Goal: %d pts",
        /* STR_HINT_TAB_ARROWS */    "Use TAB to change option, ARROWS to adjust",
        /* STR_BTN_SORT_VALUE */     "VALUE",
        /* STR_BTN_SORT_SUIT */      "SUIT",
        /* STR_DEALING */            "Dealing cards...",
        /* STR_FMT_ROUND_OF */       "Round %d of %d",
        /* STR_FMT_TURN */           "Turn: %s",
        /* STR_FMT_HAND_NO_POINTS */ "%s (no points)",
        /* STR_FMT_SELECTED */       "Selected: %d/5",
        /* STR_HINT_SELECT_CARDS */  "Select 1-5 cards to form your hand",
        /* STR_HINT_CAN_DISCARD */   "You can discard up to 5 cards",
        /* STR_FMT_PASS_DEVICE */    "Pass the device to %s",
        /* STR_ROUND_RESULTS */      "ROUND RESULTS",
        /* STR_FMT_ROUND */          "Round %d",
        /* STR_FMT_PLAYER_RESULT */  "%s - Points: +%d (Total: %d)",
        /* STR_HINT_ENTER_CONTINUE */"Press ENTER to continue",
        /* STR_GAME_OVER */          "GAME OVER",
        /* STR_FMT_WINNER */         "Winner: %s with %d points!",
        /* STR_FMT_FINAL_SCORE */    "%s: %d points (%d rounds won)",
        /* STR_HINT_RESTART */       "Press ENTER or R to restart",
        /* STR_SCOREBOARD */         "SCORE",
        /* STR_HIGH_SCORES */        "HIGH SCORES",
        /* STR_HS_PLAYER */          "Player",
        /* STR_HS_POINTS */          "Points",
        /* STR_HS_DATE */            "Date",
        /* STR_HS_EMPTY */           "No scores recorded",
        /* STR_HAND_HIGH_CARD */     "High Card",
        /* STR_HAND_ONE_PAIR */      "One Pair",
        /* STR_HAND_TWO_PAIR */      "Two Pair",
        /* STR_HAND_THREE_KIND */    "Three of a Kind",
        /* STR_HAND_STRAIGHT */      "Straight",
        /* STR_HAND_FLUSH */         "Flush",
        /* STR_HAND_FULL_HOUSE */    "Full House",
        /* STR_HAND_FOUR_KIND */     "Four of a Kind",
        /* STR_HAND_STRAIGHT_FLUSH */"Straight Flush",
        /* STR_HAND_UNKNOWN */       "Unknown",
    },
    /* ===== FR ===== */
    {
        /* STR_SUBTITLE */           "Jeu de Cartes Multijoueur",
        /* STR_BTN_PLAY */           "JOUER",
        /* STR_BTN_INSTRUCTIONS */   "INSTRUCTIONS",
        /* STR_BTN_SETTINGS */       "PARAMETRES",
        /* STR_HINT_ENTER_START */   "Appuyez sur ENTREE pour commencer",
        /* STR_HINT_BEST_HAND */     "Formez la meilleure main avec 8 cartes distribuees",
        /* STR_HOW_TO_PLAY_TITLE */  "COMMENT JOUER",
        /* STR_OBJ_LABEL */          "Objectif:",
        /* STR_OBJ_TEXT */           "Formez la meilleure main de poker avec vos cartes.",
        /* STR_HOW_TO_PLAY_SECTION */"COMMENT JOUER:",
        /* STR_INSTR_1 */            "1. Vous recevez 8 cartes",
        /* STR_INSTR_2 */            "2. Selectionnez 1-5 cartes pour former votre main",
        /* STR_INSTR_3 */            "3. Vous pouvez DEFAUSSER jusqu'a 5 cartes UNE fois",
        /* STR_INSTR_4 */            "4. Appuyez sur CONFIRMER pour jouer votre main",
        /* STR_HANDS_SECTION */      "MAINS ET POINTS:",
        /* STR_HANDS_LINE1 */        "Carte Haute: 0 pts     Paire: 100 pts      Double Paire: 200 pts",
        /* STR_HANDS_LINE2 */        "Brelan: 300 pts        Suite: 400 pts      Couleur: 500 pts",
        /* STR_HANDS_LINE3 */        "Full House: 600 pts    Carre: 800 pts      Quinte Flush: 900 pts",
        /* STR_HANDS_LINE4 */        "",
        /* STR_CONTROLS_SECTION */   "CONTROLES:",
        /* STR_CTRL_MOUSE */         "Souris: Cliquez sur les cartes pour selectionner",
        /* STR_CTRL_BUTTONS */       "Boutons: Utilisez les boutons verts pour continuer",
        /* STR_CTRL_ENTER */         "Entree: Vous pouvez aussi appuyer sur ENTREE",
        /* STR_BTN_BACK */           "RETOUR",
        /* STR_BTN_RETURN */         "REVENIR",
        /* STR_BTN_CONTINUE */       "CONTINUER",
        /* STR_BTN_NEXT */           "SUIVANT",
        /* STR_BTN_CONFIRM */        "CONFIRMER",
        /* STR_BTN_DISCARD */        "DEFAUSSER",
        /* STR_BTN_READY */          "JE SUIS PRET",
        /* STR_BTN_PLAY_AGAIN */     "REJOUER",
        /* STR_AUDIO_SETTINGS */     "PARAMETRES AUDIO",
        /* STR_LABEL_MUSIC */        "Musique:",
        /* STR_HINT_ADJUST */        "Utilisez les fleches ou + et - pour ajuster",
        /* STR_SETUP_TITLE */        "CONFIGURATION",
        /* STR_FMT_PLAYERS */        "Joueurs: %d",
        /* STR_FMT_ROUNDS */         "Manches: %d",
        /* STR_FMT_TARGET */         "Obj: %d pts",
        /* STR_HINT_TAB_ARROWS */    "TAB pour changer l'option, FLECHES pour ajuster",
        /* STR_BTN_SORT_VALUE */     "VALEUR",
        /* STR_BTN_SORT_SUIT */      "COULEUR",
        /* STR_DEALING */            "Distribution en cours...",
        /* STR_FMT_ROUND_OF */       "Manche %d sur %d",
        /* STR_FMT_TURN */           "Tour de: %s",
        /* STR_FMT_HAND_NO_POINTS */ "%s (sans points)",
        /* STR_FMT_SELECTED */       "Selectionnees: %d/5",
        /* STR_HINT_SELECT_CARDS */  "Selectionnez 1-5 cartes pour former votre main",
        /* STR_HINT_CAN_DISCARD */   "Vous pouvez defausser jusqu'a 5 cartes",
        /* STR_FMT_PASS_DEVICE */    "Passez l'appareil a %s",
        /* STR_ROUND_RESULTS */      "RESULTATS DE LA MANCHE",
        /* STR_FMT_ROUND */          "Manche %d",
        /* STR_FMT_PLAYER_RESULT */  "%s - Points: +%d (Total: %d)",
        /* STR_HINT_ENTER_CONTINUE */"Appuyez sur ENTREE pour continuer",
        /* STR_GAME_OVER */          "FIN DU JEU",
        /* STR_FMT_WINNER */         "Gagnant: %s avec %d points!",
        /* STR_FMT_FINAL_SCORE */    "%s: %d points (%d manches gagnees)",
        /* STR_HINT_RESTART */       "Appuyez sur ENTREE ou R pour recommencer",
        /* STR_SCOREBOARD */         "SCORE",
        /* STR_HIGH_SCORES */        "MEILLEURS SCORES",
        /* STR_HS_PLAYER */          "Joueur",
        /* STR_HS_POINTS */          "Points",
        /* STR_HS_DATE */            "Date",
        /* STR_HS_EMPTY */           "Aucun score enregistre",
        /* STR_HAND_HIGH_CARD */     "Carte Haute",
        /* STR_HAND_ONE_PAIR */      "Paire",
        /* STR_HAND_TWO_PAIR */      "Double Paire",
        /* STR_HAND_THREE_KIND */    "Brelan",
        /* STR_HAND_STRAIGHT */      "Suite",
        /* STR_HAND_FLUSH */         "Couleur",
        /* STR_HAND_FULL_HOUSE */    "Full House",
        /* STR_HAND_FOUR_KIND */     "Carre",
        /* STR_HAND_STRAIGHT_FLUSH */"Quinte Flush",
        /* STR_HAND_UNKNOWN */       "Inconnu",
    },
};

void LangSet(const char* code) {
    if (!code) return;
    if (code[0] == 'e' && code[1] == 's') g_lang = LANG_ES;
    else if (code[0] == 'e' && code[1] == 'n') g_lang = LANG_EN;
    else if (code[0] == 'f' && code[1] == 'r') g_lang = LANG_FR;
}

const char* T(StrKey key) {
    if (key < 0 || key >= STR_COUNT) return "";
    return s_strings[g_lang][key];
}
